# ИЗКЛЮЧЕНИЯ

Изключенията са проблем, който възниква по време на изпълнението на програма (during execution). Изключенията в C++ са отговор на извънредни обстоятелства, които възникват, докато се изпълнява програма, като опит за деление на нула.
Изключенията предоставят начин за прехвърляне на контрол от една част на програма към друга.

Ключовите думи: try , catch , throw

throw – Програма хвърля изключение, когато се появи проблем. Това се прави с помощта на ключова дума throw.

catch – Програма улавя изключение с манипулатор на изключение на мястото в програмата, където искате да се справите с проблема. Ключовата дума catch показва улавянето на изключение.

try – try идентифицира блок от код, за който ще бъдат активирани конкретни изключения. Следва един или повече блокове за хващане

# Хвърляне на изключения (throw):

Изключенията могат да бъдат хвърлени навсякъде в кодa с помощта на ключовата дума throw. Операндът на израза throw определя типa за изключението и може да бъде произволен израз, а типът на резултата от израза определя типа на изхвърленото изключение.

Пример:

```c++
double division(int a, int b)
{
    if( b == 0 )
    {
        throw "Division by zero condition!";
    }
    return (a/b);
}
```

# Улавяне на изключения (catch):

Блокът catch, следващ блока try, улавя всяко изключение. Можете да посочите какъв тип изключение искате да хванете и това се определя от декларацията за изключение, която се появява в скоби след ключовата дума catch.

```c++
try
{
    // protected code
}
catch( ExceptionName e )
{
    // code to handle ExceptionName exception
}
```

Горният код ще улови изключение от тип ExceptionName. Ако искате да посочите, че блок catch трябва да обработва всеки тип изключение, което се хвърля в блок try, трябва да поставите многоточие, ..., между скобите, обхващащи декларацията за изключението:

```c++
try
{
    // protected code
}
catch(...)
{
    // code to handle any exception
}
```
